{"ast":null,"code":"import * as i0 from \"@angular/core\";\nimport * as i1 from \"@angular/router\";\nimport * as i2 from \"@angular/common\";\n\nfunction ServerErrorComponent_ng_container_3_Template(rf, ctx) {\n  if (rf & 1) {\n    i0.ɵɵelementContainerStart(0);\n    i0.ɵɵelementStart(1, \"h5\", 2);\n    i0.ɵɵtext(2);\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementStart(3, \"p\", 3);\n    i0.ɵɵtext(4, \"Note: if you are seeing this then Angular is probably not responsible\");\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementStart(5, \"p\");\n    i0.ɵɵtext(6, \"What to do next?\");\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementStart(7, \"ol\");\n    i0.ɵɵelementStart(8, \"li\");\n    i0.ɵɵtext(9, \"Open chrome dev tools\");\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementStart(10, \"li\");\n    i0.ɵɵtext(11, \"Inspect the network tab\");\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementStart(12, \"li\");\n    i0.ɵɵtext(13, \"Check the failing request\");\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementStart(14, \"li\");\n    i0.ɵɵtext(15, \"Examine this request URL - make sure this is correct\");\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementStart(16, \"li\");\n    i0.ɵɵtext(17, \"Reproduce the error in postman - if we get the same response in postman, then the issue is NOT with angular\");\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementStart(18, \"p\");\n    i0.ɵɵtext(19, \"Following is the stack trace - this is where your investigation should start!\");\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementStart(20, \"code\", 4);\n    i0.ɵɵtext(21);\n    i0.ɵɵelementEnd();\n    i0.ɵɵelementContainerEnd();\n  }\n\n  if (rf & 2) {\n    const ctx_r0 = i0.ɵɵnextContext();\n    i0.ɵɵadvance(2);\n    i0.ɵɵtextInterpolate1(\"Error: \", ctx_r0.error.errorMessage, \"\");\n    i0.ɵɵadvance(19);\n    i0.ɵɵtextInterpolate(ctx_r0.error.details);\n  }\n}\n\nexport let ServerErrorComponent = /*#__PURE__*/(() => {\n  class ServerErrorComponent {\n    constructor(router) {\n      this.router = router;\n      const navigation = this.router.getCurrentNavigation();\n      this.error = navigation && navigation.extras && navigation.extras.state && navigation.extras.state['error'];\n      console.log(\"ss\", this.error);\n    }\n\n    ngOnInit() {}\n\n  }\n\n  ServerErrorComponent.ɵfac = function ServerErrorComponent_Factory(t) {\n    return new (t || ServerErrorComponent)(i0.ɵɵdirectiveInject(i1.Router));\n  };\n\n  ServerErrorComponent.ɵcmp = /*@__PURE__*/i0.ɵɵdefineComponent({\n    type: ServerErrorComponent,\n    selectors: [[\"app-server-error\"]],\n    decls: 4,\n    vars: 1,\n    consts: [[1, \"container\", \"mt-5\"], [4, \"ngIf\"], [1, \"text-danger\"], [1, \"font-weight-bold\"], [1, \"mt-5\", 2, \"background-color\", \"whitesmoke\"]],\n    template: function ServerErrorComponent_Template(rf, ctx) {\n      if (rf & 1) {\n        i0.ɵɵelementStart(0, \"div\", 0);\n        i0.ɵɵelementStart(1, \"h4\");\n        i0.ɵɵtext(2, \"Internal server error - refreshing the page will make the exception disapper\");\n        i0.ɵɵelementEnd();\n        i0.ɵɵtemplate(3, ServerErrorComponent_ng_container_3_Template, 22, 2, \"ng-container\", 1);\n        i0.ɵɵelementEnd();\n      }\n\n      if (rf & 2) {\n        i0.ɵɵadvance(3);\n        i0.ɵɵproperty(\"ngIf\", ctx.error);\n      }\n    },\n    directives: [i2.NgIf],\n    styles: [\"\"]\n  });\n  return ServerErrorComponent;\n})();","map":null,"metadata":{},"sourceType":"module"}